maddevsio/aws-eks-base

- .github/workflows/terraform-ci.yml
- terraform/modules/aws-ec2-pritunl/efs.tf
Added github actions to implement automatic verification of Terraform code, at the stage of checking PR and committing to all branches, performs steps:  
- `terraform-init` - Init and validate Terraform code (terraform init, terraform validate)
- `terraform-format` - Check Terraform code format (terraform fmt)
- `terraform-tflint` - Find possible problems with Terraform code linter (tflint)
Additionally formatted pritunl module `aws-ec2-pritunl/efs.tf` according to terraform format code to pass the `terraform-format` stage.
> Added github actions to check Terraform code

- terraform/layer1-aws/aws-eks.tf
- terraform/layer1-aws/demo.tfvars.example
- terraform/layer1-aws/variables.tf
- terraform/layer2-k8s/README.md
- terraform/layer2-k8s/eks-cluster-autoscaler.tf
- terraform/layer2-k8s/templates/cluster-autoscaler-values.yaml
- terraform/layer2-k8s/variables.tf
* Updated EKS kubernetes to 1.19
* Updated eks terraform module to the latest version
* Updated cluster autoscaler chart and app version
Closes #30
> eks 1.19 update

- terraform/layer2-k8s/eks-aws-node-termination-handler.tf
- terraform/layer2-k8s/eks-cert-manager.tf
- terraform/layer2-k8s/eks-certificate.tf
- terraform/layer2-k8s/eks-cluster-autoscaler.tf
- terraform/layer2-k8s/eks-cluster-issuer.tf
- terraform/layer2-k8s/eks-external-dns.tf
- terraform/layer2-k8s/eks-external-secrets.tf
- terraform/layer2-k8s/eks-kube-prometheus-stack.tf
- terraform/layer2-k8s/eks-loki-stack.tf
- terraform/layer2-k8s/eks-network-policy.tf
- terraform/layer2-k8s/eks-nginx-ingress-controller.tf
- terraform/layer2-k8s/examples/eks-alb-ingress-controller.tf
- terraform/layer2-k8s/examples/eks-apm-server.tf
- terraform/layer2-k8s/examples/eks-elasticsearch.tf
- terraform/layer2-k8s/examples/eks-elk.tf
- terraform/layer2-k8s/examples/eks-filebeat.tf
- terraform/layer2-k8s/examples/eks-gitlab-runner.tf
- terraform/layer2-k8s/examples/eks-istio.tf
- terraform/layer2-k8s/examples/eks-kibana.tf
- terraform/layer2-k8s/examples/eks-metricbeat.tf
- terraform/layer2-k8s/examples/eks-mysql-backup-wp.tf
- terraform/layer2-k8s/examples/eks-oauth2-proxy.tf
- terraform/layer2-k8s/examples/eks-postgresql-backups.tf
- terraform/layer2-k8s/examples/eks-prometheus-mysql-exporter.tf
- terraform/layer2-k8s/examples/eks-prometheus-postgresql-exporter.tf
- terraform/layer2-k8s/examples/eks-teamcity.tf
- terraform/layer2-k8s/variables.tf
Helm keeps releases history as k8s secrets. If we don't set max_history it will be unlimited.
There is an opened issue related to that https://github.com/helm/helm/issues/7997.
If count of secrets is huge then helm list/istall can be failed due to:
```
request.go:924] Unexpected error when reading response body: net/http: request canceled (Client.Timeout exceeded while reading body)
Error: unable to build kubernetes objects from release manifest: unexpected error when reading response body. Please retry. Original error: net/http: request canceled (Client.Timeout exceeded while reading body
```
> Set helm releases history size.

- terraform/layer1-aws/.terraform.lock.hcl
- terraform/layer1-aws/ebs.tf
- terraform/layer2-k8s/.terraform.lock.hcl
A lot of security benchmarks and guides recommend to use encryption for EBS volumes.
This setting enables encryption for all new EBS volumes by default even if you did not choose *Encrypted* when created it.
> Enable EBS encryption by default.

- terraform/layer2-k8s/templates/calico-values.yaml
- terraform/layer2-k8s/templates/external-secrets-values.yaml
* Changed log level for external-secrets from info to warning.
* Changed log level for calico from info to warn.
> #43 changed log-level for external-secrets and calico

- README.md
* Added Anton Babenko stream video to the readme.md
Closes #82
> #82 Added Anton Babenko stream to the README.md

- terraform/modules/aws-wafv2-top-10-owasp-rules/README.md
- terraform/modules/aws-wafv2-top-10-owasp-rules/main.tf
- terraform/modules/aws-wafv2-top-10-owasp-rules/outputs.tf
- terraform/modules/aws-wafv2-top-10-owasp-rules/variables.tf
Add terraform module to create AWS WAFv2 rule-group with rules that cover OWASP TOP 10 security issues
> Wafv2 owasp top 10

- terraform/layer1-aws/aws-eks.tf
- terraform/layer1-aws/aws-kms.tf
- terraform/layer1-aws/demo.tfvars.example
- terraform/layer1-aws/variables.tf
AWS promoted functionality to encrypt k8s secrets and configmaps using AWS KMS (https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-eks-adds-envelope-encryption-for-secrets-with-aws-kms/). 
This PR adds the option to enable this feature.
> Add option to enable eks_cluster_encryption_config

- terraform/layer2-k8s/templates/aws-node-termination-handler-values.yaml
* fixed node affinity for the node termination handler, preventing it to run on managed node groups
> #108 fixed affinity for the node termination handler

- README.md
- terraform/layer1-aws/aws-eks.tf
- terraform/layer1-aws/variables.tf
Starting from v1.18 EKS supports K8S add-ons for vpc-cni, kube-proxy, coredns. They allow us not to patch deployments/daemonsets manually. We just need to change an add-on version to the correct one.
> use EKS add-ons to install/upgrade internal components, such as vpc-cni, kube-proxy, coredns

- .github/CONTRIBUTING.md
Please explain the changes you made here and link to any relevant issues.
Fixes #142
> doc: add some notes about coding conventions

- terraform/layer1-aws/locals.tf
Fixed acm and route53 modules outputs. Removed `this_` prefix. Which was overlooked
Fixes #223
> fix: removed this prefix from r53 and acm modules outputs #223

- README.md
* Changed License banner
* Added CI status badge
Fixes #225
> doc: Changed License banner, added CI Status badge

- terraform/layer2-k8s/eks-external-secrets.tf
These changes allow external-secrets pod to get secrets from AWS Secrets Manager
Fixes #231
> bug: allow external secrets to get secrets from AWS Secrets Manager

- terraform/layer2-k8s/eks-kube-prometheus-stack.tf
- terraform/layer2-k8s/eks-prometheus-operator-crds.tf
- terraform/layer2-k8s/helm-releases.yaml
* Added server_side_apply option for `resource "kubectl_manifest" "kube_prometheus_stack_operator_crds"`
* Updated kube-prometheus-stack to version 30.1.0
* Added EKS related configuration for Prometheus
* Disabled kubeProxy alerts
Fixes #247
> bug: add server_side_apply option to kube-prometheus-stack-crd resources

- terraform/layer2-k8s/eks-aws-loadbalancer-controller.tf
We set eks_cluster_id instead of vpc_id for `vpcId` variable. This PR fixes it. 
Fixes #243
> bug: fix aws-loadbalancer-controller helm chart variables

- terraform/layer2-k8s/eks-cluster-autoscaler.tf
These changes improve cluster utilization, they allow CA (cluster-autoscaler) to scale-down nodes with utilization less than 70% (default value is 50%).
Fixes #254
> enh: change cluster-autoscaler configuration to improve cluster utilization

- terraform/layer2-k8s/eks-istio.tf
Fixed cases when Cluster Autoscaler terminates pods aren't managed by any of the k8s controllers to downscale ASG. 
Fixes #256
> fix: delete unnecessary istio-sidecar configuration

- docs/FAQ.md
- terraform/layer2-k8s/eks-gitlab-runner.tf
- terraform/layer2-k8s/helm-releases.yaml
* Updated gitlab-runner helm chart to the latest version
* Moved all deprecated options under config value
* Updated default image of gitlab-runner-executor. Changed docker registry from Docker Hub to ECR Public registry
* Fixed problems with certificates
* `Gitlab-runner can't deploy in any namespaces`.  [There is an instruction](https://github.com/maddevsio/aws-eks-base/blob/main/docs/FAQ.md)
Fixes #258
> bug: fix gitlab-runner configuration

- terraform/layer2-k8s/eks-prometheus-operator-crds.tf
Fixed problem prometheus operator is restarted continuously
Fixes [#262](https://github.com/maddevsio/aws-eks-base/issues/262#issue-1195500867) 
Delete options that are not relevant.
> bug: 262 added crd thanosrulers for prometheus stack operator

- terraform/layer2-k8s/README.md
- terraform/layer2-k8s/eks-external-secrets.tf
- terraform/layer2-k8s/helm-releases.yaml
* changed kubernetes-external-secrets to External Secrets Operator
How to use operator (for example with SecretsManager) can be found [here](https://external-secrets.io/v0.5.1/provider-aws-secrets-manager/).
Disabled global CRDs. So, we need to create SecretStore and ExternalSecret objects in necessary namespaces or enable them if it's needed. 
Fixes #275
> refactor: switch from kubernetes-external-secrets to External Secrets Operator

- terraform/layer1-aws/README.md
- terraform/layer1-aws/aws-eks.tf
- terraform/layer1-aws/aws-iam.tf
Migrated from a policy attached on instances to IRSA for vpc-cni add-on
Some notes about new locals (how they look after merging):
```
> local.eks_addon_vpc_cni
{
"addon_version" = "v1.11.0-eksbuild.1"
"resolve_conflicts" = "OVERWRITE"
"service_account_role_arn" = "arn"
}
> local.eks_addons
{
"coredns" = {
"addon_version" = "v1.8.7-eksbuild.1"
"resolve_conflicts" = "OVERWRITE"
}
"kube-proxy" = {
"addon_version" = "v1.22.6-eksbuild.1"
"resolve_conflicts" = "OVERWRITE"
}
"vpc-cni" = {
"addon_version" = "v1.11.0-eksbuild.1"
"resolve_conflicts" = "OVERWRITE"
"service_account_role_arn" = "arn"
}
}
```
Fixes #279
> enh: use k8s serviceaccount + irsa for vpc-cni add-on

- terraform/layer1-aws/README.md
- terraform/layer1-aws/aws-cloudtrail.tf
- terraform/layer1-aws/aws-eventbridge.tf
- terraform/layer1-aws/aws-s3.tf
- terraform/layer1-aws/aws-sns.tf
- terraform/layer1-aws/variables.tf
* Added possibility to notify via email about some changes in infrastructure (based on AWS [CIS Benchmark](https://docs.aws.amazon.com/config/latest/developerguide/operational-best-practices-for-cis_aws_benchmark_level_2.html), control ID: 4.1-4.15). Disabled by default.
A scheme looks like:
* Added Cloudtrail configuration because some alerts require configured Trail (for example - events from Secrets Manager)
* Wasn't able to use https://github.com/terraform-aws-modules/terraform-aws-s3-bucket to create bucket. The latest available version has political slogan. The latest version without political slogans is [v2.14.1](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/releases/tag/v2.14.1). However, it requires an AWS provider version ~> 3.69. We've recently updated aws …
> feat: CIS benchmark alerts using Eventbridge

- terraform/layer1-aws/README.md
- terraform/layer1-aws/aws-iam.tf
- terraform/layer1-aws/variables.tf
Configured AWS account password policy based on CIS recommendations. 
Fixes #286
> enh: configure AWS account password policy

- terraform/layer2-k8s/eks-cluster-autoscaler.tf
Fixed aws-cluster-autoscaler expander configuration. We switched back to self-managed nodegroups, but forgot to change aws-cluster-autoscaler configuration
Fixes #291
> bug: fix aws-cluster-autoscaler expander priorities configuration

- README.md
- docs/FAQ.md
- terraform/layer2-k8s/README.md
- terraform/layer2-k8s/eks-aws-loadbalancer-controller.tf
- terraform/layer2-k8s/eks-ingress-nginx-controller.tf
- terraform/layer2-k8s/helm-releases.yaml
* Enabled aws-load-balancer-controller by default
* Changed ingress-nginx service type from LoadBalancer to ClusterIP by default
* Disabled external-dns by default
* Generated SSL certificates for aws-load-balancer-controller due to this [issue](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2312)
* Updated FAQ.md with notes on how to terminate SSL on ingress-nginx side (use cert-manager)
New default scheme looks like:
Pros:
* we can use WAF without using Cloudfront
* we can use WebSockets
Cons:
* can be used only for http traffic
> enh: use aws-load-balancer-controller in front of ingress-nginx

- terraform/layer1-aws/aws-cloudtrail.tf
- terraform/layer1-aws/aws-vpc.tf
- terraform/layer2-k8s/eks-gitlab-runner.tf
I added the line to the file eks-gitlab-runner.tf, to fix an error for terraform plan in layer2-aws
````
count = local.gitlab_runner.enabled ? 1 : 0
`````
Fixes #304
- [ X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> fix: issue #304 layer2-aws terraform plan error

- terraform/layer1-aws/README.md
- terraform/layer1-aws/main.tf
- terraform/layer2-k8s/README.md
- terraform/layer2-k8s/main.tf
PR Description
fixed urls in "Resources" links of layer1-aws and layer2-k8s README.md
however, it was not possible to fix the links for the terraform provider kubectl. There is an open [issue](https://github.com/terraform-docs/terraform-docs/issues/679) in terraform-docs
Fixes # (https://github.com/maddevsio/aws-eks-base/issues/302)
> fixed urls Resources links in  README.md

- terraform/layer2-k8s/eks-loki-stack.tf
Set resources for Loki, otherwise it uses values from LimitRange configuration and it isn't enough. 
Fixes #318 
Delete options that are not relevant.
> fix: set k8s resources for Loki workload

- terraform/layer2-k8s/eks-kube-prometheus-stack.tf
To use the outside role, you must use the aws sdk. This method is used by default.
Fixes # (https://github.com/maddevsio/aws-eks-base/issues/343)
Delete options that are not relevant.
> fix: change authentication method for cloudwatch datasource

- docs/FAQ.md
- terraform/modules/eks-kubernetes-namespace/README.md
- terraform/modules/eks-kubernetes-namespace/variables.tf
* Deleted `cpu.limits` configuration on limitrange (namespace) level. It creates more problems than it helps
* Updated the module documentation
Fixes #345 
Delete options that are not relevant.
> enh: delete cpu.limits from the limitrange configuration

- terraform/modules/k8s-karpenter/main.tf
- terragrunt/ACCOUNT_ID/us-east-1/demo/common/aws-eks/.terraform.lock.hcl
- terragrunt/ACCOUNT_ID/us-east-1/demo/common/aws-vpc/.terraform.lock.hcl
- terragrunt/ACCOUNT_ID/us-east-1/demo/env.yaml
- terragrunt/ACCOUNT_ID/us-east-1/demo/karpenter/.terraform.lock.hcl
```
Error: karpenter/private failed to create kubernetes rest client for update of resource: resource [karpenter.sh/v1/EC2NodeClass] isn't valid for cluster, check the APIVersion and Kind fields are valid
with kubectl_manifest.ec2nodeclass_private[0],
on main.tf line 71, in resource "kubectl_manifest" "ec2nodeclass_private":
71: resource "kubectl_manifest" "ec2nodeclass_private" {
```
Solution: set `apiVersion: karpenter.k8s.aws/v1` for resources `kubectl_manifest`: `ec2nodeclass_private` and `ec2nodeclass_public` (file `terraform/modules/k8s-karpenter/main.tf`).
```
Error: karpenter/default failed to run apply: error when creating "/tmp/879917200kubectl_manifest.yaml": NodePool.karpenter.sh "default" is invalid: [spec.disruption.consolidateAfter: Required value, …
```
> fix: some fixes for karpenter deploy
